adoption/urls.py
from django.urls import path
from adoption import views


app_name = 'adoption'
urlpatterns = [
    path('', views.home, name='index'),# r means raw string
    path('detail/<int:id>', views.pet_detail, name='detail'),
]

wisdompets/urls.py
from django.contrib import admin
from django.urls import path, include

from adoption import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('adoption/', include('adoption.urls')),
]

adoption/models.py
from django.db import models


class Pets(models.Model):
    SEX_CHOICES = [
        ('M','Male'),
        ('F','Female')
    ]
    name =  models.CharField(max_length=100)
    submitter = models.CharField(max_length=100)
    species = models.CharField(max_length=30)
    breed = models.CharField(max_length=30, blank=True) #means can exist withour a breed
    description = models.TextField()
    sex = models.CharField(choices=SEX_CHOICES, max_length=1, blank=True)
    submission_date = models.DateTimeField()
    age = models.IntegerField(null=True)

    def __str__(self):
        return self.name


class Vaccine(models.Model):
    name = models.CharField(max_length=50)
    has_reason = models.ManyToManyField(Pets, through='Reason')

    def __str__(self):
        return f"Vaccine name is {self.name}"


class Reason(models.Model):
    pets = models.ForeignKey(Pets, on_delete=models.CASCADE)
    vaccine = models.ForeignKey(Vaccine, on_delete=models.CASCADE)
    reason_for = models.TextField()

    def __str__(self):
        return (self.pets.name+" was given "+ self.vaccine.name+" vaccine for "+self.reason_for+".")

adoption/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404

from .models import Pets, Reason


def home(request):
    pets_info = Pets.objects.all()
    return render(request,"home.html",{"pets_info" : pets_info})


def pet_detail(request, id):
    context = {}
    try:
        pet_info = Pets.objects.get(id=id)
        vacc = Reason.objects.filter(pets=pet_info)
        context = {
                    "pet_info":pet_info,
                    "vaccine":vacc,
                   }
        print(vacc.count())
    except Pets.DoesNotExist or Reason.DoesNotExist:
        raise Http404("Pet is not present.")

    return render(request, "pet_detail.html", context)

adoption/templates/base.html
{% load static %}
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <title>Home - Wisdom Pet Medicine</title>
        <link rel="stylesheet" id="ample-style-css" href="{% static 'style.css' %}" type="text/css" media="all">
    </head>
    <body class="wide">
        <div id="page" class="hfeed site">
            <header>
                <div class="header">
                    <div class="main-head-wrap inner-wrap clearfix">
                        <div id="header-logo-image">
                            <a href="/">
                                <img src="{% static 'images/logo.png' %}" alt="Wisdom Pet Medicine">
                            </a>
                        </div>
                        <div id="header-text" class="">
                            <h1 id="site-title">
                                <a href="/" title="Wisdom Pet Medicine" rel="home">Wisdom Pet Medicine</a>
                            </h1>
                            <p>We treat your pets like we treat our own.</p>
                        </div>
                    </div>
                    <img src="{% static 'images/header.jpg' %}" alt="Wisdom Pet Medicine">
                </div>
            </header>
            <div class="main-wrapper">
                <div class="single-page clearfix">
                    <div class="inner-wrap">
                        <p>Wisdom Pet Medicine strives to blend the best in traditional and alternative medicine in the diagnosis and treatment of health conditions in companion animals, including dogs, cats, birds, reptiles, rodents, and fish. We apply the latest healthcare technology, along with the wisdom garnered in the centuries old tradition of veterinary medicine, to find the safest and most effective treatments and cures, while maintaining a caring relationship with our patients and their guardians.</p>
                        <hr>
                        <div>
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
            <footer id="colophon">
                <div class="inner-wrap">
                    Wisdom Pet Medicine is a fictitious brand created by Lynda.com, solely for the purpose of training. All products and people associated with Wisdom Pet Medicine are also fictitious. Any resemblance to real brands, products, or people is purely coincidental. Please see your veterinarian for all matters related to your pet's health.
                </div>
            </footer>
        </div>
        <script src="{% static 'main.js' %}"></script>
    </body>
</html>

adoption/templates/home.html
{% extends "base.html" %}
{% block content %}
<div>
    {% for pet in pets_info %}
    <div class="petname">
        <a href="{% url 'adoption:detail' pet.id %}">
            <h3> {{ pet.name }} </h3>
        </a>
        <p>Species : {{ pet.species }}</p>
        <p>Breed : {{ pet.breed }}</p>
        <p class="hidden">Description : {{ pet_info.description }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

adoption/templates/pet_detail.html
{% extends "base.html" %}
{% block content %}
<div>
    <h3>{{ pet_info.name }}</h3>
    <p>Species : {{ pet_info.species }}</p>
    {% if pet_info.breed %}
        <p>Breed : {{ pet_info.breed }}</p>
    {% endif %}
    {% if pet_info.sex %}
        <p>sex : {{ pet_info.sex }}</p>
    {% endif %}
    {% if pet_info.age %}
        <p>Age : {{ pet_info.age }}</p>
    {% endif %}
    {% if vaccine %}
    <p>Vaccine:</p>
    {% for reason in vaccine.all %}
    <ul>
        <li>{{ reason.vaccine.name }}: {{ reason.reason_for }}</li>
    </ul>
    {% endfor %}
    {% endif %}
    <p class="hidden">Description : {{ pet_info.description }}</p>
    <p>Submitted By: {{ pet_info.submitter }}</p>
    <p>Submitter On: {{ pet_info.submission_date }}</p>
</div>
{% endblock %}